# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7a22843c9ab0e730ad790128f0d538374895159022b12c739e63c55100c30666348b768dfbb1f80a4fed0104a4f544590c8a6014bf96085787e46409f04a961

test:
  secret_key_base: fd3e7c71862d592b577400e1855b1a5e1a334ca05a45842a943b90b8bd8a9bf78a70ded64aba7576d7235287b370ca235c6fe3a20bbcd53a558f168f9ad2ab21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
